### PR TITLE
Add Python 3.4 support

### PR DESCRIPTION
**Pull request by sYnfo**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@rhcarvalho FYI

**Comment by rhcarvalho** [comment]
Ideally adding new versions should change two or three strings in a few files.
I understand making it that way has not been a priority so far. Do we have plans on removing the multiple copies of S2I scripts and test files? This applies to all language builders.

Other than that, LGTM.

**Comment by mfojtik** [comment]
@rhcarvalho do you know if we have trello card to refactor images to share common scripts?

**Comment by rhcarvalho** [comment]
@mfojtik now we do: https://trello.com/c/Ovt1qgfX/659-refactor-s2i-builder-images-to-share-common-scripts-and-tests-across-multiple-versions-of-a-builder-image

**Comment by sYnfo** [comment]
@mfojtik @rhcarvalho Is this OK to be merged, then? :)

**Comment by rhcarvalho** [comment]
Yes. @bparees please merge this.

**Comment by soltysh** [comment]
:clap: for having python 3.4 support!

**Comment by bparees** [comment]
working on merging this, need to setup a couple things in our jenkins job.

**Pull request merged**
