### PR TITLE
Sync Red Hat build service labels

### PR DESCRIPTION
**Pull request by praiskup**
Related: openshift/postgresql/pull/75

### CODE REVIEW

**Comment by praiskup** [comment]
AFAIK we don't build rh-python27-docker, I'm not sure what should be
done with 2.7 directory.

**Comment by mfojtik** [comment]
@praiskup @bparees IMHO we keep the old values for backward compatibility

**Comment by bparees** [comment]
wait, SCL isn't shipping a python2.7 image?

**Comment by bparees** [comment]
Just to clarify, after discussion with PM,  2.7 should be being built/shipped by SCL.

**Pull request merged**
